#!/bin/bash
cd /tarpaulin

# Avoid any merge commits generated by travis (screws up coveralls reporting)
git checkout $TRAVIS_BRANCH

# Run tests and send code coverage report to coveralls
cargo tarpaulin --coveralls $COVERALLS_TOKEN --report-uri https://coveralls.io/api/v1/jobs
