FROM rust:1.38

RUN apt-get update && \
    apt-get install -y libzmq3-dev unzip protobuf-compiler && \
    apt-get clean

RUN curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
    && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
    && rm protoc-3.5.1-linux-x86_64.zip
